module "this" {
  source                     = "../terraform-aws-vpc"
  cidr_block                 = var.cidr_block
  project_name               = var.project_name
  enable_dns_hostnames       = var.enable_dns_hostnames
  common_tags                = var.common_tags
  vpc_tgas                   = var.vpc_tags
  igw_tags                   = var.igw_tags
  aws_nat_gateway_tags       = var.aws_nat_gateway_tags
  public_subnet_cidr_block   = var.public_subnet_cidr_block
  public_subnet_tags         = var.public_subnet_tags
  private_subnet_cidr_block  = var.private_subnet_cidr_block
  private_subnet_tags        = var.private_subnet_tags
  database_subnet_cidr_block = var.database_subnet_cidr_block
  database_subnet_tags       = var.database_subnet_tags
  public_route_table_tags    = var.public_route_table_tags
  private_route_table_tags   = var.private_route_table_tags
  database_route_table_tags  = var.database_route_table_tags
  roboshop_db_subnet_group   = var.roboshop_db_subnet_group
} 